### ISSUE TITLE
Add files by pattern but for drag & drop

### ISSUE THREAD

**Issue by Gorrrg** [enzo1982/freac#83] opened 2020-02-12 22:25 UTC
**Is your feature request related to a problem? Please describe.**
When I drag and drop a folder into the main window, fre:ac adds all files it recognizes (and even files that it doesn't recognize spouting out error messages).

**Describe the solution you'd like**
Add an option in the settings where the user can define include **and** exclude patterns. Ideally in a list of items that can be individually added and removed and not by using wild cards. But give the user that alternative to use wildcards instead, maybe even using regular expressions. That'd be really neat.

**Describe alternatives you've considered**
- Using the menu File->Add->Audio file(s)->By pattern
- Use an external tool to create a playlist to import, for instance if regular expressions are needed to match files

**Comment by enzo1982** [comment] 2020-02-14 19:34
Thank you for your suggestion! However, I'm not convinced this would be a worthwile addition to fre:ac.

First, there already is the _"Add files by pattern"_ feature that enables you to add only certain file types.

Second, this can also be achieved easily with external tools like Total Commander (search for files [allows multiple patterns, using regex, searching by file time etc.], then select the results and drag and drop them into fre:ac).

And last but not least, I can see users trying this feature, setting it to *.m4b, then forgetting about it and coming back after one month wondering and creating tickets about fre:ac not accepting their FLAC and MP3 files.

So, for now I am not going to implement this. However, if someone else does and submits a patch, I will consider integrating it in fre:ac.

**Comment by Gorrrg** [comment] 2020-02-15 01:06
Ok, that makes sense. And I can see how it would be quite overkill for something that you can simply use your file management shell for. But unfortunately this doesn't work in Windows 10. When I want to drag and drop File Explorer's search results into the fre:ac window nothing happens. When I drag and drop from a non-search result view, it does work.

**Comment by enzo1982** [comment] 2020-02-15 10:25
Drag and drop from an Explorer search result to fre:ac works for me. There seems to be an issue with Explorer, though, when dragging a search result outside of the Explorer window. Explorer freezes for a moment and you have to keep holding the mouse button down until it unfreezes. After that, you can drop the files on fre:ac or elsewhere.

I had a search result of 185 files and Explorer froze for ~18 seconds when dragging the files out of its window. Then tried with only 60 files and got a ~6 second delay. So it seems to be ~0.1s per file which could grow quite big when you have a lot of files in the search result. Looks like a bug in Explorer to me.

Please try if you can reproduce this behavior.

**Comment by Gorrrg** [comment] 2020-02-15 15:41
Even though file explorer's search is very buggy at the moment, because it has been completely overhauled recently, I think it's something else.

I did some drag and drop testing with other programs selecting different selections of files and it turns out that it must be the actual string that gets passed from the file explorer. I have changed my registry to allow NTFS file paths to be longer than 255. And by shift right-clicking in the explorer and choosing "Copy as path" I found what breaks drag and drop for some files.

Paths that are longer than 255 are formatted slightly differently than the ones shorter than 256 characters. They all start with `\\?\`. So "D:\Musiv\longpath" becomes "\\?\D:\Music\longpath".

So it actually has nothing to do with the list of search results being different than a normal list of files in a folder. When I try to drag and drop those files with a very long path from their actual folder it doesn't work either.

**Comment by enzo1982** [comment] 2020-02-15 17:37
OK, I see. I can reproduce this now with a long file name.

The reason this does not work is not the prepended `\\?\` prefix. Actually, Windows does not generate `WM_DROPFILES` messages for such file names. The `IDropTarget` OLE interface is used instead and is not currently implemented by fre:ac.

I'll see if I can fix this for the next update.

**Comment by Gorrrg** [comment] 2020-02-15 18:21
Ah, cool!

**Comment by enzo1982** [comment] 2020-02-16 14:12
The drag & drop issue is now fixed with commit enzo1982/smooth@e7dcdf57.

I made a version for you to test again: [freac-1.1-beta3-dndfix-windows-x64.zip](https://github.com/enzo1982/freac/files/4209828/freac-1.1-beta3-dndfix-windows-x64.zip)

**Comment by Gorrrg** [comment] 2020-02-16 16:25
I can confirm that it works with long file paths now. :)

**Comment by enzo1982** [comment] 2020-02-16 17:34
Great! Thank you for verifying this!

**Closed** 2020-02-16 17:34 UTC
Labels: enhancement
