### ISSUE TITLE
Crash after opening General Settings

### ISSUE THREAD

**Issue by timg7** [enzo1982/freac#128] opened 2020-07-02 12:33 UTC
Freac crashes with a segmentation fault after opening the General Settings window.

**To Reproduce**
Launch Freac
Open General Settings via menu or toolbar
Click "OK" or "Cancel"

Happens with fresh installation and no changes to settings
Freac v1.1.2 and v1.1.1 tested with identical behaviour

**System**
MacOS Catalina 10.15.5
Macbook
8GB RAM

Freac can run as long as the General Settings window is never opened.
Changing settings in "Configure Selected Encoder" does not cause a crash

**Comment by enzo1982** [comment] 2020-07-02 20:30
Cannot reproduce this here with macOS 10.15.5.

Could you attach the crash details here please? Click Details in the crash reporter window.

**Comment by timg7** [comment] 2020-07-02 22:02
Hi Robert,
After some more testing, the crash seems to be triggered by the system tab preferences:
Apple -> System Preferences -> Dock -> Prefer tabs when opening documents -> Always
Crash details attached.

[freaccrash.txt](https://github.com/enzo1982/freac/files/4866824/freaccrash.txt)

**Comment by enzo1982** [comment] 2020-07-02 22:34
Dang! I can reproduce this now with the tabbed documents setting enabled. Thank you for providing this additional info!

I'll see what I can do to fix this. Appears to be related to the menu bar implementation in the class library used by fre:ac. That's where your crash log says it crashed and I'm also seeing this in a debug build on my system.

**Comment by enzo1982** [comment] 2020-10-11 16:43
This should be fixed with the fre:ac 1.1.3 update.

**Closed by enzo1982** 2020-10-11 16:43 UTC
Labels: bug
