### ISSUE TITLE
Can*t add audio files in folder to freeac (MacOS)

### ISSUE THREAD

**Issue by Olli0073** [enzo1982/freac#251] opened 2021-12-01 15:37 UTC
Can't add files in Folder via drag and drop to programm window. Can*t add a folder via Open menu. Can add only files.
Freeac hangs up. One core shows 100% workload. Freeac don't react.
I have this bus with this build and penultimate Version.

Can you add a history of old versions for Continuous builds.
**To Reproduce**
Grab a folder with audio files and put it on the freeac windows.

 - OS: MacOS 12.0.1 Monterey
 - MACOS11.DMG
 - CPU: M1
 - RAM: 8 GB]

**Comment by enzo1982** [comment] 2021-12-06 01:19
Thank you for reporting this! This should be fixed in the latest continuous build now.

The issue was caused by a recently added feature that enables adding playlist files to the joblist by drag & drop. When dropping a folder, the new code triggered a bug in the file I/O layer that would open a folder as if it were a file on most non-Windows platforms. Trying to actually read from such a file handle would then lead to an infinite loop, causing the program to freeze.

**Comment by enzo1982** [comment] 2022-01-23 00:49
Closing this as fre:ac 1.1.6 has been released with the fix.

**Closed by enzo1982** 2022-01-23 00:49 UTC
Labels: bug
