### ISSUE TITLE
Genre Use for all selected track not accessible

### ISSUE THREAD

**Issue by rodandersen** [enzo1982/freac#259] opened 2022-01-16 21:12 UTC
I updated to 1.1.4 and now I can access the drop down menu to set the genre for all selected tracks. Very annoying. I have moved the mouse all along as it's visible but never get to the button before it disappears. 
Using windows 10

**Comment by enzo1982** [comment] 2022-01-17 00:09
Duplicate of #192.

This was a bug in fre:ac 1.1.4 and has long been fixed in the 1.1.5 update. Please update to 1.1.5.

**Closed by enzo1982** 2022-01-17 00:09 UTC
Labels: bug, duplicate
