### ISSUE TITLE
Version 1.1.7 hard crashes

### ISSUE THREAD

**Issue by nilsbeck** [enzo1982/freac#530] opened 2023-09-01 09:08 UTC
**Describe the bug**
Freac crashes hard, and a window to send the issue to apple appears.

**To Reproduce**
1. Open freac, have a CD in your drive (I newly installed freac, no custom settings made)
2. Click on 'add audio cd content to the job list'
3. freac crashes hard, closes and the apple error report window appears.

**Expected behavior**
The CD data is read and I can then rip the data.

**System (please complete the following information)**
 - OS: macOS Ventura 13.5.1 (22G90)
 - CPU: M1
 - RAM: 16GB

**Additional context**
I downloaded version 1.1.6 from GH and everything works as expected.

**Comment by kohnworkshop** [comment] 2023-09-15 15:47
I'm having the same issue. Crash on CD load.
Running upgraded 1.1.7 (from 1.1.5 which worked) on imac with apple silicon.

**Comment by Lee-Carre** [comment] 2023-09-17 02:46
> Steps to reproduce the behavior:
> 
> 1. Open freac, have a CD in your drive (I newly installed freac, no custom settings made)
> 2. Click on 'add audio cd content to the job list'
> 3. freac crashes hard, closes and the apple error report window appears.
> 
> […]
> 
> **System (please complete the following information)**
> * OS: macOS Ventura 13.5.1 (22G90)
> * […]

Can't reproduce on non-[cr]Apple OSes. So, is either contextual (eg configuration) or something AppleBSD-specific.

What happens when (either of) you try the [Continuous Build](/enzo1982/freac/releases/tag/continuous)?

**Comment by nilsbeck** [comment] 2023-09-18 08:00
hey,

I just tried the build you linked and this works now. I can read the disc and start ripping without any crashes.

**Comment by kohnworkshop** [comment] 2023-09-18 14:08
Hi,
I was not able to try this until today and got a invalid url notice below.
(BTW version 1.1.6 works fine)

[image: Screenshot 2023-09-18 at 4.06.01 PM.png]

Daniel Kohn
kohnworkshop.com
oceanmemoryproject.com

**Comment by kohnworkshop** [comment] 2023-09-18 14:13
But I then found the continuous build online and it works for me as well.
Thank you!

Daniel Kohn
kohnworkshop.com
oceanmemoryproject.com

**Comment by Lee-Carre** [comment] 2023-09-25 00:04
Glad that you both have functioning instances, now.

In that case, since the problem is fixed in source-code, please could the OP close this ticket.

**Closed** 2023-09-25 03:33 UTC
Labels: bug

**Comment by Lee-Carre** [comment] 2023-10-07 21:13
Seems that the cause was fixed in https://github.com/enzo1982/freac/commit/efb9f510fbe333be313cf98a19c83e2b8b349a68, the comment of which suggests that it was to do with the `libcdio`.

**Comment by Lee-Carre** [comment] 2023-10-07 23:22
Future reference; duplicate of #457.
