### ISSUE TITLE
Skipping in playback

### ISSUE THREAD

**Issue by ghost** [enzo1982/freac#141] opened 2020-08-01 09:43 UTC
After the conversion using Lame 100 mp3, I recognized a skip of one second during playback, where there was no skipping like that in the orginal file.

**Comment by enzo1982** [comment] 2020-08-01 13:25
Please attach the source file and resulting MP3 or send them to support@freac.org to allow me to verify the issue.

Also, please provide information about your system and settings (operating system and version, fre:ac version used, LAME encoder settings used).

**Comment by enzo1982** [comment] 2020-08-02 17:23
Thank you for sending the files! I was able to identify the issue and implement a fix.

The problem was caused by an edge-case not handled by the MP3 bitstream repacker that could lead to invalid bitstreams being written in rare cases.

Here's a fixed version of the LAME encoder component: [boca_encoder_lame.1.0.zip](https://github.com/enzo1982/freac/files/5012504/boca_encoder_lame.1.0.zip)

This is for the 64 bit version of fre:ac. Just replace the existing version of boca_encoder_lame.1.0.dll in the boca folder with the one from the ZIP file to apply the fix.

**Comment by EugeneDay35** [comment] 2020-08-02 17:41
You are fantastic. I forgot to write my window's bit version. Unfortunately, it is 32 bit win 7 😯☹🙁Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Robert Kausch <notifications@github.com> Date: 8/2/20  20:23  (GMT+03:00) To: enzo1982/freac <freac@noreply.github.com> Cc: EugeneDay35 <ergungun@gmail.com>, Author <author@noreply.github.com> Subject: Re: [enzo1982/freac] Skipping in playback (#141) 
Thank you for sending the files! I was able to identify the issue and implement a fix.
The problem was caused by an edge-case not handled by the MP3 bitstream repacker that could lead to invalid bitstreams being written in rare cases.
Here's a fixed version of the LAME encoder component: boca_encoder_lame.1.0.zip
This is for the 64 bit version of fre:ac. Just replace the existing version of boca_encoder_lame.1.0.dll in the boca folder with the one from the ZIP file to apply the fix.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/enzo1982/freac/issues/141#issuecomment-667701702",
"url": "https://github.com/enzo1982/freac/issues/141#issuecomment-667701702",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by enzo1982** [comment] 2020-08-02 18:10
Alright, nevermind. Here's the 32 bit version: [boca_encoder_lame.1.0.zip](https://github.com/enzo1982/freac/files/5012554/boca_encoder_lame.1.0.zip)

**Comment by EugeneDay35** [comment] 2020-08-03 10:11
Solved. Perfect support. Wish you the best in the market.

**Comment by enzo1982** [comment] 2020-10-11 16:48
fre:ac 1.1.3 is now available with the fix for this issue.

**Closed by enzo1982** 2020-10-11 16:48 UTC
Labels: bug
