### ISSUE TITLE
Unable to specify output directory in OS X 12.0.1

### ISSUE THREAD

**Issue by jimmodo** [enzo1982/freac#248] opened 2021-11-29 02:31 UTC
**Describe the bug**
After importing the audio files to be converted, you are not able to select the output directory.  You receive an error:

The open file operation failed.

The open file operation failed to connect to the open and save panel service.

[OK]

**To Reproduce**
1. Import music
2. Click on 'Select'
3. See error

**Expected behavior**
Open dialogue appears.

**Screenshots**
<img width="372" alt="Screen Shot 2021-11-28 at 18 29 04" src="https://user-images.githubusercontent.com/27605738/143799395-69872d85-d3f7-48bf-8582-07e3377f4220.png">

**System (please complete the following information)**
 - OS: 12.0.1
 - CPU: M1 Macbook Air (2020)
 - RAM: 8 GB

**Comment by enzo1982** [comment] 2021-11-29 23:52
Duplicate of #238 and #245.

There's a bug in macOS Monterey causing file panel issues. This is fixed with a work-around in the [continuous builds](https://github.com/enzo1982/freac/releases/continuous) as mentioned in the [Downloads](https://www.freac.org/downloads-mainmenu-33) section on freac.org:

> _**Users of macOS Monterey:**_ please use the [Continuous Build](https://www.freac.org/downloads-mainmenu-33/308-freac-continuous) for now which fixes an issue with the file dialog of fre:ac 1.1.5 when running on the current version of macOS Monterey; an official release with the fix will be available shortly

As I haven't finished the official 1.1.6 release yet, I think I will make a hotfix release for macOS this week. This is much 
simpler and quicker than a full release.

**Comment by enzo1982** [comment] 2021-12-09 00:27
This is now fixed in the official fre:ac 1.1.5a hotfix. Closing this issue.

**Closed by enzo1982** 2021-12-09 00:27 UTC
Labels: bug
