### ISSUE TITLE
When converting from FLAC to WMA 9.2 Lossless, covert art image metadata does not get transferred to the WMA file

### ISSUE THREAD

**Issue by bernardy2** [enzo1982/freac#406] opened 2022-12-17 22:28 UTC
I am performing conversions of FLAC audio files with FLAC metadata tags to WMA 9.2 Lossless. When I examine the WMA metadata in Mp3tag or foobar2000 after conversion, it appears the text metadata tags are ported correctly, but the cover art image is not ported at all.

1. Add .FLAC files with cover art image metadata to the job list.
2. Set the encoder to Windows Media Audio 9.2 Lossless
3. Run conversion
4. Examine metadata of the converted WMA file in a media player or tag viewer.

**Expected behavior**
Cover Art image metadata transferred successfully to the WMA file. 

**System (please complete the following information)**
 - OS: Windows 11 build 22623.1037
 - fre:ac v 1.1.6 x86-64

I can use Mp3tag to add the cover art images to the WMA file, so I don't think there are any format limitation issues to the image tag porting, so probably a bug?

I've tried WMA 9.2 Lossy and WMA 10 Professional. Again, the cover art image fails to port.
Also tried Lame MP3 as the encoder, and the cover art does port properly. So it seems restricted to the WMA encoder.

**Comment by enzo1982** [comment] 2022-12-18 00:56
I cannot reproduce this here. Cover art is transferred to the output file when converting to WMA and foobar2000 and Mp3tag both show the cover art from the files' tags.

Please check the following fre:ac options:

- Is the _WMA Metadata_ tag format enabled on the _Tags_ page of the configuration dialog?
- Is _WMA Metadata_ enabled as a target format for writing cover art to tags on the _Cover art_ tab of the _Tags_ configuration page?

Both options should be enabled by default, so this is just to rule out that you disabled them before.

**Comment by bernardy2** [comment] 2022-12-18 19:34
Sorry, I did not have WMA Metadata enabled in the cover art tab. I didn't notice the separate cover art tab. Thank you. You can close this issue.

**Closed** 2022-12-18 20:46 UTC
Labels: bug
