### ISSUE TITLE
Problem with tag when encoding aac

### ISSUE THREAD

**Issue by AndyBebendi** [enzo1982/freac#333] opened 2022-06-22 08:55 UTC
Hi, when I convert mp3 files or other types of music files to aac format, the output files are missing the tags that were present in the source files. This is not the case when I convert from flac to mp3. Can you help me? Is this a bug? thank you

**Comment by enzo1982** [comment] 2022-06-25 17:05
Hi, are you converting to .aac format or .m4a format?

Usually, AAC is wrapped in .m4a container files which have good support for tagging, so you should see your tags in the output files. If, however, you are creating .aac files, you'll need to enable ID3v2 tagging in the AAC encoder settings (usually that's the FDK-AAC or Core Audio encoder settings).

On the _Format_ tab, where you select betwen MP4 (.m4a) and AAC format, there is an option to enable ID3v2 tagging. Several players have issues handling .aac files with such tags, though, which is why tagging .aac files is disabled by default.

If possible in your use case, use the MP4 output option to create .m4a files.

**Comment by enzo1982** [comment] 2023-03-06 23:31
Closing this assuming this is not a bug and the question is answered.

**Closed by enzo1982** 2023-03-06 23:31 UTC
Labels: bug
