### ISSUE TITLE
Original modified and created date is not preserved when transconding to the same format

### ISSUE THREAD

**Issue by Gorrrg** [enzo1982/freac#80] opened 2020-02-12 22:05 UTC
**Describe the bug**
Original modified and created date is not preserved when transcoding from FLAC to FLAC when this option is set.

**To Reproduce**
1. Set the option "Keep time stamps of source files", "Encode on-the-fly", "Use input folder if possible", "Allow overwriting of input files", "Filename pattern: \<filename\>"
2. Set encoder to FLAC
3. Add some FLAC files and encode
4. Check the file time stamps.

**Expected behavior**
The modified and created time stamps should match those of the originals.

**System (please complete the following information)**
 - OS: Windows 10
 - CPU: Intel Core i7 6700K
 - RAM: 16 GB
 - fre:ac version: 1.1 beta 3

**Comment by enzo1982** [comment] 2020-02-13 22:01
I cannot reproduce this issue.

When converting FLAC to FLAC using the options you list, both, the creation and modification time stamps of the files are kept (although the former is not actively managed by fre:ac).

I tried with files on different file systems (NTFS and FAT32), with and without Unicode characters in the file names and with and without the "Encode on-the-fly" option. The result was the same in each case, both time stamps were kept.

When converting to a new file (i.e. not using <filename> as the output pattern), it behaves like you describe in your other bug ticket (#81).

**Comment by enzo1982** [comment] 2020-02-13 22:10
I did some more experiments and it turns out that when the _"Enable output verification"_ option is checked, the modification time stamp indeed gets lost.

I'll provide a fix soon.

**Comment by enzo1982** [comment] 2020-02-13 22:51
This should be fixed now with commit 313e2d8f.

You can try this updated version: [freac-1.1-beta3-filetimefix-windows-x64.zip](https://github.com/enzo1982/freac/files/4201808/freac-1.1-beta3-filetimefix-windows-x64.zip)

**Comment by Gorrrg** [comment] 2020-02-15 00:09
Cool, it works now. Yup, I also had "Enable output verification" enabled, I didn't think it mattered so I didn't mention it.

**Comment by enzo1982** [comment] 2020-02-15 10:06
Great! Thanks for reporting back!

**Closed by enzo1982** 2020-02-15 10:06 UTC
Labels: bug
