### ISSUE TITLE
When converting to MP3 from M4A/AAC, audio becomes garbled or sped up on some songs

### ISSUE THREAD

**Issue by jed-development** [enzo1982/freac#253] opened 2021-12-04 18:42 UTC
**Describe the bug**
When converting some songs to MP3 from AAC, the audio becomes garbled or sped up, when in previous versions with the same conversion it didn't. It first started in version 1.1.4, it appears to be fine in 1.1.3. The only real difference I can see is a different decoder for AAC was introduced between the 2 versions (see screenshots)

**To Reproduce**
1.  Under encoder settings, set use preset to custom settings and change VBR quality setting to 0.
2. Once set, add a song to encode as MP3 from AAC such as Selena Gomez - She
3. Once encoded, audio will sound slightly garbled and sped up in places. It doesn't do this on default encoding settings.

**Expected behavior**
The audio file should convert to MP3 without becoming garbled or sped up.

**Screenshots**

![freac_04-12-2021_16 43 52](https://user-images.githubusercontent.com/49375041/144717524-2aa9801a-120b-4271-9571-16b8d37d42b6.png)
This screenshot shows the first decoder in 1.1.3.

![freac_04-12-2021_16 45 56](https://user-images.githubusercontent.com/49375041/144717525-5ad80b0b-33a9-4679-a59b-c78f55075164.png)
This screenshot shows the second decoder in 1.1.4, also present in 1.1.5.

![freac_04-12-2021_18 09 26](https://user-images.githubusercontent.com/49375041/144720194-6ce93c2b-427d-4122-aecd-76c8c51839a8.png)
Audio encoder settings as mentioned in the reproduction steps.

**System**
 - OS: Windows 10 21H2, Build 19044.1348
 - CPU: AMD Ryzen 5 5600X
 - RAM: 16GB

**Additional context**
This only seems to happen on some audio files, such as Selena Gomez - She or Kungs - Never Going Home

**Comment by enzo1982** [comment] 2021-12-04 19:34
Thank you for reporting this!

I'm already investigating this issue as another user reported it via email. I can confirm that it's related to the switch to the FDK-AAC decoder. Apparently some files use AAC parameters in certain frames that FDK-AAC considers invalid. The decoder then skips those frames which results in garbled output.

The issue is not limited to fre:ac. The other user was able to reproduce the same behavior with an Android media player. Android is using FDK-AAC as its system AAC decoder.

I already have some sample files to reproduce this. Next step will be to figure out whether the files are actually using invalid parameters (which would mean there's a buggy encoder involved) or FDK-AAC is rejecting valid files (which would be a bug in FDK-AAC).

**Comment by enzo1982** [comment] 2021-12-04 23:32
Turned out to be an FDK-AAC bug indeed.

Fortunately, there already is [a fix](https://android.googlesource.com/platform/external/aac/+/67cae74f74bce961e0812c1743c64df96a3396b7%5E!/#F0) in the Android code base. I'm including this in fre:ac builds now. The [continuous builds](https://github.com/enzo1982/freac/releases/tag/continuous) already have the patch, so please use those for now.

I also opened an issue in the [libfdk-aac project](https://github.com/mstorsjo/fdk-aac) asking for an update to the latest upstream code.

**Comment by enzo1982** [comment] 2022-01-23 00:48
Closing this as fre:ac 1.1.6 has been release with the fix.

**Closed by enzo1982** 2022-01-23 00:48 UTC
Labels: bug
