### ISSUE TITLE
GUI bug/White Text under elementary OS 5.1.7 Hera

### ISSUE THREAD

**Issue by sudot0ph** [enzo1982/freac#171] opened 2020-11-18 20:49 UTC
**Describe the bug**
Font in GUI defaults to #FFFFFF

**Screenshots**
![Bildschirmfoto von 2020-11-18 21-44-02](https://user-images.githubusercontent.com/43375596/99586114-8b870d00-29e7-11eb-9cd1-2e319750fdff.png)

**System (please complete the following information)**
 - OS: elementary OS 5.1.7 Hera; Pantheon/GTK 3.22.30
 - CPU: Intel® Core i3-2350M CPU @ 2.30GHz
 - RAM: 4 GB

**Comment by enzo1982** [comment] 2020-11-19 01:15
Thank you for reporting this!

I can reproduce this and can confirm it's related to how fre:ac uses the GTK theme. I'll look for a solution.

**Comment by enzo1982** [comment] 2020-11-20 18:53
The issue is fixed in the latest continuous build.

**Comment by enzo1982** [comment] 2021-02-15 11:46
Closing this as fre:ac 1.1.4 is now available with the fix for this.

**Closed by enzo1982** 2021-02-15 11:46 UTC
Labels: bug
