### ISSUE TITLE
wrong name in first output sub folder?

### ISSUE THREAD

**Issue by k2z3k0** [enzo1982/freac#198] opened 2021-03-21 19:00 UTC
hi

when converting whole folder ,first sub folder and sample comments have name of main folder and not of fisrt sub folder

https://user-images.githubusercontent.com/31962256/111916875-61208b80-8a7d-11eb-92a0-0ca9a904c792.png

 - OS: mb pro 2010 high sierra
 - CPU: intel i5
 - RAM: 4gb

**Comment by enzo1982** [comment] 2021-03-21 22:35
Apparently your .wav files do not contain any tags, thus title information recognition from file and folder names is triggered.

The issue is then caused by the number in the folder name, which makes the recognition heuristic think it might name a disc number.

This is not really a bug. When there are no tags, anything that is recognized by the algorithm is guesswork and needs to be checked manually before starting the conversion (the tracks in question would have been listed with artist _Movie Samples_ in the joblist).

However, I will change the algorithm to perform more checks before assuming a folder name contains a disc number. Additional criteria will be:

- Keywords like _CD_, _disc_ or a translation of the word _disc_ in the folder name (e.g. _3 Doors Down_ will no longer be considered as a disc number, but _2nd Disc_ will)
- The number of words in the folder name (must be less than 3 unless a keyword is present)
- More than one number present in the folder name (e.g. _NOS4A2_ will no longer be considered as a disc number)

It's still lots of guessing, of course, but it will always be. When your input files are not tagged, applications can only take a guess which will go wrong relatively often and you will need to manually check the recognized information. Better just add tags to your .wav files and fre:ac and other applications will use those.

**Comment by k2z3k0** [comment] 2021-03-22 07:47
Got it
Thank you for replay

Best regards


http://soundcloud.com/k2z3k0
http://mixcloud.com/k2z3k0

**Comment by enzo1982** [comment] 2021-06-28 19:08
fre:ac 1.1.5 is now available with the improved metadata recognition heuristics. Closing this.

**Closed by enzo1982** 2021-06-28 19:08 UTC
Labels: bug
