### ISSUE TITLE
operator[]: illegal array index: X of X: errno: 34 (./src/mp4array.h,128)

### ISSUE THREAD

**Issue by krothschild** [enzo1982/freac#76] opened 2020-02-02 11:04 UTC
**Describe the bug**
When converting multiple m4b or m4a files to a single m4a, even ones that freac have "ripped" from CD, it complains about the final entry in the array:

**To Reproduce**
for x in ~/to-convert/*;  do    /Applications/freac.app/Contents/MacOS/freaccmd -e coreaudio -b 32 -o "$x.m4a" "$x/*";  done

**Expected behavior**
No error.

**Screenshots**

Processing file: ...operator[]: illegal array index: 15319 of 15319: errno: 34 (./src/mp4array.h,128)
operator[]: illegal array index: 730 of 730: errno: 34 (./src/mp4array.h,128)
done.

**System (please complete the following information)**
 - OS: macOS Catakuba 10.15.1
 - CPU: Quad-Core Intel Core i7 2.8 Ghz
 - RAM: 16 GB

**Additional context**

**Comment by enzo1982** [comment] 2020-02-02 12:25
Thank you for reporting this!

This is actually something I was aware of for some time and wanted to investigate at some point. It's apparently a bug in the MP4v2 library, but seems to be non-critical as it is detected and reported by the library itself.

I'll see if can track this down before the fre:ac 1.1 beta 3 release.

**Comment by enzo1982** [comment] 2020-02-09 22:46
I was unable to reproduce this issue on macOS, but did so on Linux and Windows and fixed it there. Please check if this is fixed with fre:ac 1.1 beta 3.

**Comment by krothschild** [comment] 2020-02-10 11:43
Fix confirmed - I was not able to reproduce the issue with the new code!
THANKS!

**Closed** 2020-02-10 12:01 UTC
Labels: bug
