### ISSUE TITLE
Failed to verify output

### ISSUE THREAD

**Issue by stpr-dev** [enzo1982/freac#299] opened 2022-04-18 03:17 UTC
**Describe the bug**
When trying to convert an FLAC to m4a, I am a dialog box saying "Failed to verify input" (see log below). This always happens to this one file. Happens on both Windows and Linux.

**To Reproduce**
1. Add file to joblist.
2. Select an output format and click convert.
3. Get the dialog box (output file is still created).

**Expected behavior**
Conversion should be successful without any dialog box.

**Log**
```
Conversion #4 - 1 tracks

Client:  fre:ac - free audio converter
Version: v1.1.6 (20220402) (x86-64)

System:  Windows 10 Pro (Release 2009, Build 19044)
CPU:     AMD Ryzen 7 1700 Eight-Core Processor          
RAM:     32 GB

Date:    2022-04-03
Time:    16:46:10

hh:mm:ss.fff
------------
00:00:00.436 Starting conversion process...
00:00:00.436     Selected encoder:     Core Audio AAC/ALAC Encoder
00:00:00.436     Parallel processing:  Enabled (up to 12 threads)
00:00:00.436         SuperFast mode:   Enabled
00:00:00.436 
00:00:00.436     Output settings:      Multiple files
00:00:00.437         Filename pattern: <albumartist> - <album>\<track> - <artist> - <title>
00:00:00.437 
00:00:00.459     Converting: 27 Girlfriend Records - Crypt of the Necrodancer- The Synthwave Cuts MEGAMIX.flac
00:00:00.459             to: Girlfriend Records - Crypt of the Necrodancer Synthwave Cuts ULTIMATE EDITION\27 - Girlfriend Records - Crypt of the Necrodancer The Synthwave Cuts MEGAMIX.m4a
00:00:00.459         Replacing existing file with conversion result
00:00:00.459         Decoder: FLAC Audio Decoder v1.3.4
00:00:00.460 
00:00:05.612     Failed to verify input file: 27 Girlfriend Records - Crypt of the Necrodancer- The Synthwave Cuts MEGAMIX.flac
00:00:05.612         Expected: 3f6c237a731bd893b5606a03bc93f968
00:00:05.612 
00:00:06.006     Finished converting: 27 Girlfriend Records - Crypt of the Necrodancer- The Synthwave Cuts MEGAMIX.flac
00:00:06.006         Duration: 00:05.546 (364.4x speed)
00:00:06.006 

```

**System (please complete the following information)**
 - OS: Windows 10 / Arch Linux
 - CPU: Ryzen 7 1700
 - RAM: 32 GB

**Additional context**
Not sure why this specific file, all other files work fine. Anything to do with the size? This particular file is 230.7 MiB (30+ mins), which is particularly large.

**Comment by enzo1982** [comment] 2022-04-18 19:09
The message _"Failed to verify input file"_ means that the checksum of the decoding result does not match the original audio checksum stored in the FLAC file.

This is most likely caused by a damaged input FLAC file and the most common cause for this would be a disk failure. There may be other explanations, however, including but not limited to:

- A memory bit-flip occurring during encoding, leading to a bad value stored in the FLAC file or a bad checksum
- A broken CPU used for encoding (e.g. overclocked CPUs can produce erroneous results)
- A bug in the FLAC encoder or decoder

The message simply indicates that something went wrong trying to decode the FLAC file and the decoding result most likely does not match the audio originally stored in the FLAC file. There is no way for fre:ac to tell what caused this mismatch.

You can check the file with the command line `flac` tool to possibly get more information like this: `flac -t file.flac`

If you think that your file is not damaged, you might want to contact the [FLAC project](https://github.com/xiph/flac) about this. It is theoretically possible that a bug in the FLAC encoder or decoder may lead to output differing from the original audio. The error is much more likely to be caused by faulty hardware, though. As far as I know, most of such cases reported to the FLAC project before could be traced back to faulty hardware or issues introduced by overclocked components.

In any case, this does not look like a bug in fre:ac, so I'm closing this here.

**Closed by enzo1982** 2022-04-18 19:09 UTC
Labels: bug

**Comment by stpr-dev** [comment] 2022-04-18 23:21
Thanks for the information, you are right that this seems to be an issue with the specific file. `flac -t` did result in an error, so I redownloaded the file and it passed the test with no issues. A bit concerning that I might be having hardware issues, but at least I am in the right track.

**Comment by enzo1982** [comment] 2022-04-19 18:04
Oh, if the file was downloaded, it's likely that the error was introduced during the download. Maybe it was incomplete.

I wouldn't worry too much about the possibility of the error being caused by a hardware issue in this case.
