### ISSUE TITLE
Monkey's Audio not appearing in Encoder lists

### ISSUE THREAD

**Issue by Masterfireheart** [enzo1982/freac#78] opened 2020-02-07 03:51 UTC
**Describe the bug**
Monkey's Audio encoder appears to be missing from the program on both 1.1 Beta 1 and 2

**To Reproduce**
1. Go to select an encoder in any menu, or go to the "Encoders" section of the settings.

**Screenshots**
![freac_w0DkYIwLy6](https://user-images.githubusercontent.com/6299186/73999143-f8ca2580-4920-11ea-9340-cd5f7b694131.png)

**System (please complete the following information)**
 - OS: Windows 10 (1909) (18363.592)
 - CPU: AMD Ryzen 9 3900X
 - RAM: 32GB

**Additional context**
The encoder files between Alpha 20190423 and both Betas appear the same, it doesn't seem like anything's missing there.

**Comment by enzo1982** [comment] 2020-02-07 10:02
Thank you for reporting this!

I can confirm that the Monkey's Audio encoder is missing in the 64 bit Windows build of fre:ac 1.1 beta 1 and beta 2. The reason is a parameter type mismatch in the declaration and definition of one function exported by the MACDll library.

This will be fixed in beta 3.

**Closed** 2020-02-07 23:53 UTC
Labels: bug
