### ISSUE TITLE
Missing tracks using freaccmd for ripping on Win10

### ISSUE THREAD

**Issue by dr-leo** [enzo1982/freac#106] opened 2020-04-14 12:48 UTC
Hi,

first, a big thank you for creating and maintaining and improving this fantastic Project for so Long.

Now let me describe what I consider a bug:

I have been using recent to current (v1.1) versions issuing roughly the following command on Win10:

```
freaccmd -d somedir --cddb -t all --Encoder=some_encoder -p <Album>/<track>_<title>
```

In About 40-50% of CDs, one or two tracks are missing in the Output dir. So I issue the same command with `-t xx` with xx being the missing track number. In most cases, the missing track is then converted properly and placed into the Output dir. 

Any help would be appreciated.

**Comment by enzo1982** [comment] 2021-02-15 13:30
Sorry for not replying earlier! I was unable to reproduce this issue until another user later reported similar behavior when converting files.

The issue was related to fre:ac's internal conversion job management. In some cases, jobs were removed from one queue, but then deleted before they had been added to the next one. This was effectively causing fre:ac to _"forget"_ about some tasks.

This should be fixed now in fre:ac 1.1.4.

**Closed by enzo1982** 2021-02-15 13:30 UTC
Labels: bug
