### ISSUE TITLE
http://freedb.freac.org/ not working

### ISSUE THREAD

**Issue by matthew-jurewicz** [enzo1982/freac#180] opened 2020-12-19 00:35 UTC

**Comment by matthew-jurewicz** [comment] 2020-12-19 00:41
Some error occurred trying to connect to the free DB server.

**Comment by enzo1982** [comment] 2020-12-19 01:55
Please update to the latest version of fre:ac. fre:ac 1.1.3 should automatically switch the freedb.freac.org server over to gnudb.gnudb.org.

If you are getting this error when trying to submit entries to the database and the issue persists after upgrading to fre:ac 1.1.3, using the continuous build version should help. It has some fixes for CDDB submission that will be in the upcoming fre:ac 1.1.4.

fre:ac continuous builds are available for Linux. If you need a version with the fixes for Windows or macOS, let me know.

**Comment by matthew-jurewicz** [comment] 2020-12-19 02:16
Thanks for your response! I need a continuous build for Windows

**Comment by Asmido** [comment] 2020-12-19 10:48
I'm on 1.1.3 and for me gnudb.gnudb.org doesn't work since yesterday. freedb.freac.org works, but only for a single CD at a time, when I insert another CD without closing, reopening and setting freedb.freac.org again, it freezes.

**Comment by enzo1982** [comment] 2020-12-19 13:31
@matthew-jurewicz Please use this build I made for another user a week ago: https://freac.org/updates/freac-1.1.3-20201210-windows-x64.zip

However, after @Asmido's message, I tested the GnuDb service and it seems they are having issues right now. I can confirm it's working only sometimes - most of the time it's timing out and I get the _"Some error occurred trying to connect to the freedb server."_ message.

This is an issue at GnuDb's end. I'm getting the same timeout trying to open www.gnudb.org in the browser right now.

As for freedb.freac.org, please make sure the HTTP POST or HTTP GET access mode is selected in the CDDB settings. The server behind freedb.freac.org does not support the CDDBP access mode. Both HTTP modes are working for me here.

**Comment by enzo1982** [comment] 2020-12-20 11:51
www.gnudb.org is back online with a note confirming a technical issue. It should now be fixed and CDDB queries in fre:ac should be working again.

**Closed** 2021-03-18 00:10 UTC
Labels: bug
