### ISSUE TITLE
FDK-AAC Encoder v4.0.1: looks like Q1 is actually Q3 and Q3 is Q1 when Maximum bandwidth is not set to auto

### ISSUE THREAD

**Issue by igv** [enzo1982/freac#212] opened 2021-05-12 06:05 UTC
This is file sizes (in Mb) at each Q and various max bandwidths (tested on multiple files of course):
| |Q5|Q4|Q3|Q2|Q1
|---|---|---|---|---|---|
| 19 kHz   | 9.2 | 7.0 | 5.5 | 5.7 | 6.0
| 18 kHz   | 9.9 | 8.0 | 6.6 | 6.9 | 7.1
| 17.5 kHz | 8.7 | 6.6 | 5.1 | 5.4 | 5.6
| 16.5 kHz | 9.2 | 7.4 | 6.1 | 6.3 | 6.5
| 16 kHz   | 8.2 | 6.2 | 4.8 | 5.0 | 5.3
| 15 kHz   | 8.5 | 6.8 | 5.5 | 5.7 | 5.9
| 14.5 kHz | 7.6 | 5.7 | 4.4 | 4.6 | 4.9
| 13.5 kHz | 7.6 | 6.0 | 4.8 | 5.0 | 5.2

Don't know if it's a freac bug or libfdk...
Posting here because easy workaround.

**Comment by enzo1982** [comment] 2021-05-13 23:12
This is not a bug.

According to the FDK-AAC documentation, Q1 is optimized for HEv2 AAC, while Q2 is tuned for HEv1. If you use those modes with LC AAC you will get strange results.

I will add a note to the configuration dialog to warn about using Q1 and Q2 with LC AAC.

**Comment by igv** [comment] 2021-05-15 06:11
Results are not that strange. File size is always larger. Does that mean quality is always better (at the same bandwidth)?
Btw, currently, Q1 + 17.5 kHz average file size is approx. the same as Vorbis Q3 (also 17.5 kHz).

**Comment by igv** [comment] 2021-05-15 07:13
What is strange is auto-bandwidth:  Q1/Q2 - 13 kHz, Q3 - 16 kHz, Q4 - 16.5 kHz.

**Comment by enzo1982** [comment] 2021-05-15 10:21
> Does that mean quality is always better (at the same bandwidth)?

No. Bitrate is only indirectly related to quality and higher bitrate does not automatically mean higher quality.

> What is strange is auto-bandwidth: Q1/Q2 - 13 kHz, Q3 - 16 kHz, Q4 - 16.5 kHz.

Not strange at all. Q1 and Q2 are optimized for HE/HEv2 AAC which use Spectral Band Replication (SBR) to reproduce higher frequencies on the decoder side. So the frequency cut-off for the LC part is expected to be relatively low.

That's probably also why you get those high bitrates when forcing higher frequencies. The Q1 and Q2 mode are not designed to handle such high frequencies, so to deal with them, bitrate has to be ramped up.

**Comment by enzo1982** [comment] 2021-06-28 19:18
The FDK-AAC configuration dialog has been updated in fre:ac 1.1.5 to no longer allow Q1-2 for LC-AAC and Q1 for HE-AAC. The available modes are:

- LC-AAC: Q3-5
- HE-AAC: Q2-5
- HEv2-AAC: Q1-5
- LD-AAC: Q3-5
- ELD-AAC: Q1-5

Closing this.

**Closed by enzo1982** 2021-06-28 19:18 UTC
Labels: question
