### ISSUE TITLE
fre:ac crashes when changing title attributes

### ISSUE THREAD

**Issue by Qaldak** [enzo1982/freac#71] opened 2020-01-11 09:45 UTC
Hi

If I try to change any title informations like artist, album, title etc. fre:ac closes / crashes immediately. The crash happens already on click in the attribut.

I could'nt find any information about the failure.

If I start fre:ac from terminal, I get follow information:
```
++ WARN: CD-TEXT: Invalid use of Tab Indicator.
Speicherzugriffsfehler
```

In sylog or kern.log I only found these entries about fre:ac: 
```
Jan 11 10:40:52 elementaryOS kernel: [ 1453.486575] show_signal_msg: 19 callbacks suppressed
Jan 11 10:40:52 elementaryOS kernel: [ 1453.486578] freac[12107]: segfault at 0 ip 00007f1f443056e4 sp 00007fff1d32f180 error 4 in libX11.so.6.3.0[7f1f442bb000+135000]
Jan 11 10:40:52 elementaryOS io.elementary.m[4337]: message repeated 91 times: [ noise_playback_manager_get_current_media: assertion 'self != NULL' failed]
Jan 11 10:40:52 elementaryOS wingpanel[1776]: gee_abstract_map_get: assertion 'self != NULL' failed
Jan 11 10:40:52 elementaryOS wingpanel[1776]: gee_abstract_map_set: assertion 'self != NULL' failed
Jan 11 10:40:52 elementaryOS io.elementary.m[4337]: noise_playback_manager_get_current_media: assertion 'self != NULL' failed
```

I run fre:ac v1.1 Beta 1 (20200109) on linux, elementary OS 5.1 Hera

**Comment by enzo1982** [comment] 2020-01-11 16:08
Thank you for reporting this!

I installed elementary OS 5.1 in a VM and tried to reproduce this, but no crash is happening here. I think this issue might be related to some keyboard input fixes I made before the Beta 1 release. Could you try if the crash also happens with the 20190423 version?

And do you have any special keyboard input methods activated or customized you system in any unusual way?

**Comment by Qaldak** [comment] 2020-01-12 10:38
OK.  I installed version 20190423 (incl re-install smooth, BoCa). With this version (fre:ac v1.1 Beta 1), I can change the field values. fre:ac doesn't crash aynmore.

No, nothing special. It crashes already on set the cursor into field (with mouse click).

**Comment by enzo1982** [comment] 2020-01-12 23:30
OK, thank you for trying the previous alpha and confirming it works.

I made some changes to make cursor handling more robust today and included them in the beta 2 release as a last minute change.

Could you try that version please? I still cannot reproduce the issue, but I think there's a small chance that these changes may fix it.

**Comment by Qaldak** [comment] 2020-01-14 20:28
I installed Beta 2 directly from github and it works properly.

But I found the reason: If I install freac from snapshop (sudo snap install freac --beta) then it crashs if I set the cursor into a field. 
So the problem is only, if I use snap-version.

**Comment by Qaldak** [comment] 2020-01-14 20:30
For me it's ok. I can use the github-way to install fre:ac. 
You can close this issue if you want.

**Comment by enzo1982** [comment] 2020-01-14 23:35
OK, I tried the Snap on elementary OS and I can reproduce the crash now! The Snap runtime uses different versions of some libraries compared to the main system, which can lead to different behavior.

I will keep this issue open and try to find out what's going wrong in the next few days.

**Comment by enzo1982** [comment] 2020-01-16 23:05
This is fixed in the latest edge channel Snap now.

In hindsight the bug was quite obvious, a missing null check on the input manager instance. The Xlib provided by the Snap runtime seems to behave different than the system's Xlib in that the former returns a null pointer in the absence of a running input manager, while the latter returns a dummy input manager instance. Thus the crash only when using the Snap.

Please reopen if not fixed for you, but I double checked with the old and new version, so I'm quite confident it's working now. 😉

**Closed by enzo1982** 2020-01-16 23:05 UTC
Labels: bug
